#!/bin/bash

PATH=\
:./\
:/usr/local/bin/\
:/usr/bin/\
:/usr/sbin/\
:/sbin/\
:/bin/\
:$HOME/bin/\
:$HOME/bin/lib/\
:$HOME/.local/bin/\
:./\;
export PATH

#python path
#:$HOME/python/\
PYTHONPATH=\
:./\;
export PYTHONPATH

##PROMPT
export PS1="\u:"
export PS2="\u@\h:"
#export PS#="$PWD"

#GIT
# PATH=/usr/local/git/:/usr/local/git/bin:${PATH}

#MAVEN
#export M2_HOME=/Users/al/Local/maven*
#export M2=${M2_HOME}/bin
#PATH=${M2}:${PATH}

## editor
export EDITOR=/usr/bin/vi


## ALIAS
alias h='history'
alias x='exit'
alias la='ls -a'
alias ll='ls -al'
alias cp='cp -iv'
alias mv='mv -iv'
alias cl='clear'
alias sa='source activate gl-env'

export JAVA_HOME=$(/usr/libexec/java_home)


# added by Anaconda2 2.5.0 installer
export PATH="/Users/marshall/anaconda/bin:$PATH"

# added by Anaconda3 5.0.1 installer
export PATH="/Users/marshall/anaconda3/bin:$PATH"
